---
- name: Copy website file template
  template:
    src: index.html.j2
    dest: "{{ host_volume }}"
- name: Create Apache container
  docker_container:
    name: webapp
    image: "{{ apache_image }}"
    ports:
      - "80:80"
    volumes: 
      - "{{ host_volume }}":"{{ container_volume }}"
